const {
    PROJECT_ID,API_KEY,DATABASE_ID,PATIENT_COLLECTION_ID,APPIONTMENT_COLLECTION_ID,DOCTOR_COLLECTION_ID,
    NEXT_PUBLIC_BUCKET_ID: PMS_BUCKET,
    NEXT_PUBLIC_ENDPOINT: ENDPOINT
} = process.env;